services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    shm_size: 256mb
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
