"""create table tax_rates

Revision ID: 06f24c3125af
Revises: aebaaaa691ea
Create Date: 2025-02-02 16:45:43.035693

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "06f24c3125af"
down_revision: Union[str, None] = "aebaaaa691ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tax_rates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tax_type", sa.Enum("PIS", "COFINS", "CLSS", name="tax_types"), nullable=False),
        sa.Column("tax_period", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_tax_rate", sa.Float(), nullable=False),
        sa.Column("presumide_tax_rate", sa.Float(), nullable=True),
        sa.Column("withholding_tax_rate", sa.Float(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("base_tax_rate >= 0", name="base_tax_rate_gte_zero"),
        sa.CheckConstraint("presumide_tax_rate >= 0", name="presumide_tax_rate_gte_zero"),
        sa.CheckConstraint(
            "withholding_tax_rate is null or withholding_tax_rate >= 0", name="withholding_tax_rate_gte_zero"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tax_type_active_per_type_period",
        "tax_rates",
        ["tax_type", "tax_period"],
        unique=True,
        postgresql_where="active = TRUE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tax_type_active_per_type_period", table_name="tax_rates", postgresql_where="active = TRUE")
    op.drop_table("tax_rates")
    # ### end Alembic commands ###
