"""initial migration

Revision ID: aebaaaa691ea
Revises:
Create Date: 2025-02-01 23:23:41.292424

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "aebaaaa691ea"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
